import { HttpClient } from "@angular/common/http";
import { NewsSecData } from "./news-page.component";
import * as xml2js from 'xml2js';

export class HealthLoader {
  responseTest: any = {
    "id": "tq7X9v2dKgkTre59",
    "title": "bmw",
    "description": "#bmw generated by RSS.app",
    "source": {
      "url": "https://rss.app/rss-feed?keyword=bmw"
    },
    "items": [
      {
        "title": "BMW Brings Alpina Performance Brand into the Fold",
        "url": "https://www.caranddriver.com/news/a39396769/bmw-alpina-performance-brand-added/",
        "description": "After 57 years, the highly respected small tuning firm is being acquired by the automaker, and after 2025 we can expect all future Alpina models to come straight from BMW.",
        "author": "Mike Duff",
        "publishedAt": "2022-03-10T09:36:00.000Z",
        "thumbnail": {
          "url": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2022-bmw-alpina-b8-gran-coupe-4-1646929819.jpg?crop=0.702xw:0.527xh;0.126xw,0.284xh&resize=640:*",
          "mimeType": "image/jpeg"
        }
      },
      {
        "title": "Quick Look: 2022 BMW M 1000 RR—Ultimate Evolution, In The April Issue",
        "url": "https://www.roadracingworld.com/news/quick-look-2022-bmw-m-1000-rr-ultimate-evolution-in-the-april-issue/",
        "description": "BMW's M 1000 RR, the company's most advanced and highest-performing streetbike, on track in the April 2022 issue of Roadracing World magazine.",
        "publishedAt": "2022-04-08T18:30:57.000Z",
        "thumbnail": {
          "url": "https://www.roadracingworld.com/wp-content/uploads/2022/04/0422_QL_BMW_A_Toye-8-M1000RR-DSC_0699_P_WEB-A_1649440221.jpg",
          "mimeType": "image/jpeg"
        }
      },
      {
        "title": "BMW M2 G87 Seats Leak Might not be the Original Ones",
        "url": "https://www.bmwblog.com/2022/04/07/bmw-m2-g87-seats-leak/",
        "description": "BMW community quickly reposted the new seats as a leak of the carbon bucket seats found in the upcoming BMW M2 G87.",
        "publishedAt": "2022-04-07T21:35:51.000Z",
        "thumbnail": {
          "url": "https://cdn.bmwblog.com/wp-content/uploads/2022/03/2023-bmw-m8-carbon-bucket-seats-00-scaled.jpg",
          "mimeType": "image/jpeg"
        }
      }
    ]
  };
  axRss: string = "https://raw.githubusercontent.com/JoshGoodman22/Verum1Test/master/src/assets/RSSFeeds/Trending/Health/AxiosHealth2.xml";
  reutersRss: string = "https://raw.githubusercontent.com/JoshGoodman22/Verum1Test/master/src/assets/RSSFeeds/Trending/Health/ReutersHealth2.xml";
  unRss: string = "https://raw.githubusercontent.com/JoshGoodman22/Verum1Test/master/src/assets/RSSFeeds/Trending/Health/UNHealth2.xml";
  apRss: string = "https://raw.githubusercontent.com/JoshGoodman22/Verum1Test/master/src/assets/RSSFeeds/Trending/Health/APHealth22.xml";

  constructor(private http: HttpClient) { }

  loadData() {
    let data: NewsSecData = {
      title: "Health",
      mainImgDec: "Loading...",
      mainImgDeclink: "Loading...",
      image: "",
      Subheadline1: "Loading...",
      Subheadline1link: "Loading...",
      Subheadline2: "Loading...",
      Subheadline2link: "Loading...",
      Subheadline3: "Loading...",
      Subheadline3link: "Loading..."
    }

    this.getAxios(data);
    this.getReuters(data);
    this.getUN(data);
    this.getAP(data);

    return data;
  }

  getReuters(newsData: NewsSecData) {
    console.log(this.responseTest.items);
    console.log(this.responseTest.items[0])
    console.log(this.responseTest.items[0].title)
    console.log(this.responseTest.items[0].url)
    console.log(this.responseTest.items[0].thumbnail.url)
    newsData.Subheadline1 = this.responseTest.items[0].title;
    
    newsData.Subheadline1link = this.responseTest.items[0].url;
    newsData.image = this.responseTest.items[0].thumbnail.url;
    // this.http.get(this.reutersRss, { responseType: "text" }).subscribe((data) => {
    //   const parser = new xml2js.Parser({ strict: false, trim: true });
    //   parser.parseString(data, (err, result) => {
    //     newsData.Subheadline1 = "(Reuters) " + result.RSS.CHANNEL[0].ITEM[1].TITLE[0];
    //     newsData.Subheadline1link = result.RSS.CHANNEL[0].ITEM[1].LINK[0];
    //   });
    // });
  }

  getAxios(newsData: NewsSecData) {
    this.http.get(this.axRss, { responseType: "text" }).subscribe((data) => {
      const parser = new xml2js.Parser({ strict: false, trim: true });
      parser.parseString(data, (err, result) => {
        // newsData.image = result.RSS.CHANNEL[0].ITEM[0].DESCRIPTION[0].SRC;
        ; newsData.mainImgDec = "(Axios) " + result.RSS.CHANNEL[0].ITEM[0].TITLE[0];
        newsData.mainImgDeclink = result.RSS.CHANNEL[0].ITEM[0].LINK[0];
      });
    });
  }


  getUN(newsData: NewsSecData) {
    this.http.get(this.unRss, { responseType: "text" }).subscribe((data) => {
      const parser = new xml2js.Parser({ strict: false, trim: true });
      parser.parseString(data, (err, result) => {
        newsData.Subheadline2 = "(UN) " + result.RSS.CHANNEL[0].ITEM[4].TITLE[0];
        newsData.Subheadline2link = result.RSS.CHANNEL[0].ITEM[4].LINK[0];
      });
    });
  }

  getAP(newsData: NewsSecData) {
    this.http.get(this.apRss, { responseType: "text" }).subscribe((data) => {
      const parser = new xml2js.Parser({ strict: false, trim: true });
      parser.parseString(data, (err, result) => {
        newsData.Subheadline3 = "(CBS) " + result.RSS.CHANNEL[0].ITEM[0].TITLE[0];
        newsData.Subheadline3link = result.RSS.CHANNEL[0].ITEM[0].LINK[0];
      });
    });
  }
}